# Name of the GitHub Actions workflow
name: .NET Blazor CI Pipeline

# Defines when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Environment variables used across jobs
env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_NAME: 'software-engineering--blazor-pipeline.csproj'

jobs:
  build-and-test:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore Dependencies
      run: dotnet restore ${{ env.PROJECT_NAME }}
    
    # Updated code formatting check
    - name: Check Code Formatting
      run: |
        dotnet tool install -g dotnet-format
        dotnet format ${{ env.PROJECT_NAME }} --verify-no-changes --verbosity diagnostic
    
    - name: Build
      run: dotnet build ${{ env.PROJECT_NAME }} --configuration Release --no-restore
    
    - name: Install Coverage Tool
      run: dotnet tool install --global coverlet.console
    
    - name: Run Tests with Coverage
      run: |
        dotnet test ${{ env.PROJECT_NAME }} \
          --configuration Release \
          --no-build \
          --verbosity normal \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover \
          /p:CoverletOutput=./coverage/ \
          /p:Threshold=80 \
          /p:ThresholdType=line,branch,method
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./coverage/coverage.opencover.xml