# Name of the GitHub Actions workflow
name: .NET Blazor CI Pipeline

# Defines when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Environment variables used across jobs
env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'TodoTestSuite.sln'
  PROJECT_PATH: 'src/TodoTestSuite/TodoTestSuite.csproj'

jobs:
  build-and-test:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore Dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
    
    - name: Check Code Formatting
      run: |
        dotnet tool install -g dotnet-format
        dotnet format ${{ env.SOLUTION_FILE }} --verify-no-changes --verbosity diagnostic
    
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

    
    - name: Run Tests with Coverage
      run: dotnet test ${{ env.SOLUTION_FILE }} \
          --configuration Release \
          --no-build \
          --verbosity normal \
          --collect:"Code Coverage;Format=Xml;CoverageFileName=coverage.xml" \
          --results-directory ./coverage
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./coverage/coverage.xml